kind: pipeline
name: blog

clone:
  disable: true

steps:
  # api unit test
  - name: blog-web
    image: node:11
    commands:
      - git clone git@github.com:Colunmdear/blog.git
      - npm install
      - npm run docs:build
trigger:
  branch:
    - master
  event:
    - pull_request
    - push
