kind: pipeline
name: api
steps:
  # api unit test
  - name: test
    image: node:11
    depends_on: [clone]
    commands:
      - npm install --registry https://registry.npm.taobao.org
      - npm install
      - npm run docs:build
trigger:
  branch:
    - master
  event:
    - pull_request
    - push
---
#stream test
kind: pipeline
name: stream
steps:
  - name: stream test
    image: ccr.ccs.tencentyun.com/star/stream-test-base
    commands:
      - echo 'Hello!'
trigger:
  branch:
    - stream
  event:
    - pull_request
