kind: pipeline
name: blog
steps:
  # api unit test
  - name: blog-web
    image: node:11
    depends_on: [clone]
    commands:
      - npm install
      - npm run docs:build
trigger:
  branch:
    - master
  event:
    - pull_request
    - push
